### ISSUE TITLE
no all data is exporting in xml

### ISSUE THREAD

**Issue by ManthanBudheliya** [flownative/neos-trados#10]
Hello,

I have created a simple basic demo site, and I have added 3 content elements and 1 page in root page.

When I try to export the data, the xml file contains only below given details, there is no any change in xml file if I try to export after adding and removing the content element from page.

Here is the xml file data.

`<?xml version="1.0" encoding="UTF-8"?>
<content name="Demo Site" sitePackageKey="Site.Demo" workspace="live" sourceLanguage="en">
 <nodes formatVersion="1.0"/>
</content>
`

**Comment by kdambekalns** [comment]
Can reproduce this with Neos 3.3

**Comment by ixtensa** [comment]
Hello,
can you give any information when this bug will be fixed?

**Comment by kdambekalns** [comment]
No. I started to look into it, but paid work and family have priority. So, no estimate right now, sorry.

**Comment by skurfuerst** [comment]
Hey,

are you sure this is happening? For me this happens when the dimension configured in `Settings.yaml` is wrong, i.e. 

```
Flownative:
  Neos:
    Trados:
      languageDimension: 'language_country'
```

All the best,
Sebastian

**Comment by kdambekalns** [comment]
Thanks for the hint… I hope this is solved and you have not given up, @ixtensa … 😬
