### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by ManthanBudheliya** [flownative/neos-trados#9]
How can I install this plugin with Neos setup?

Doing `composer require flownative/neos-trados` gives following error within composer
http://nimb.ws/Lbn6Ed

Can anybody help here?

**Comment by kdambekalns** [comment]
Yeah, the pacjage was not registered at packagist yet. Did that now…

**Comment by kdambekalns** [comment]
Added hint on installation to README.md and tagged version 2.0.0 of the package for Neos 3.x.
